Robot: Robot2
Hostname: 192.168.015
LineDetection:
    Amout Of Error In LineDetection: 3
    Amout OF Refresh: 10
Battery:
    Charged Level: 23.9
Ready Area:
    Line Location:
        X:  7.48
        Y:  -6.5
        Angle: 0
    Position In Line:
        Max: 13.0
        Min: 13.0
Charge Area:
    Url: 192.168.0.201
    Line Location:
        X:  7.48
        Y:  -6.5
        Angle: 0
    Position In Line:
        Max: 13.0
        Min: 13.0
Robot Determined Goal Position:
    Error Vx: 0.0001
    Error Vy: 0.0001
    Error W: 0.0001
    Error Dx: 0.8
    Error Dy: 0.8 
    
        